version: '3'
services:
  app:
    container_name: full_app
    build: .
    ports: 
      - "8080:8080"
    environment:
      - SERVER_ADDRESS=${SERVER_ADDRESS}
      - POSTGRES_CONN=${POSTGRES_CONN}
    restart: on-failure
    volumes:
      - ./src:/usr/src/app/
    depends_on:
      - fullstack-postgres        
    networks:
      - fullstack

  fullstack-postgres:
    image: postgres:latest
    container_name: full_db_postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - fullstack

networks:
  fullstack:

volumes:
  database_postgres:
